{% set name = "torch-geometric" %}
{% set version = "1.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/cc/b2/19eca95445f4657d6f164e3b57342f138780cca2b4a96a7f1a80707d778a/torch_geometric-1.3.0.tar.gz"
  sha256: "a37f36e7277eb76c0198ac6af4841ddf3e21038e11022388b3b2483e0e80724e"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - h5py
    - networkx
    - numpy
    - pandas
    - pip
#    - plyfile ==0.7
    - python
#    - rdflib ==4.2.2
    - scikit-learn
    - scipy
    - pytest-runner
    - pytorch ==1.1.0
  run:
    - h5py
    - networkx
    - numpy
    - pandas
#    - plyfile ==0.7
    - python
#    - rdflib ==4.2.2
    - scikit-learn
    - scipy
    - torch-sparse
    - torch-scatter
    - torch-cluster
    - requests

test:
#  imports:
#    - torch_geometric
#    - torch_geometric.data
#    - torch_geometric.datasets
#    - torch_geometric.nn
#    - torch_geometric.nn.conv
#    - torch_geometric.nn.dense
#    - torch_geometric.nn.glob
#    - torch_geometric.nn.models
#    - torch_geometric.nn.pool
#    - torch_geometric.nn.unpool
#    - torch_geometric.read
#    - torch_geometric.transforms
#    - torch_geometric.utils
#    - torch_geometric.visualization
  requires:
#    - torch-sparse
#    - torch-scatter
#    - torch-cluster
    - pytorch ==1.1.0
    - mock
    - pytest
    - pytest-cov

about:
  home: "https://github.com/rusty1s/pytorch_geometric"
  license: "UNKNOWN"
  license_family: "OTHER"
  license_file: ""
  summary: "Geometric Deep Learning Extension Library for PyTorch"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
