{% set name = "torch-cluster" %}
{% set version = "1.4.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/bd/5f/01c5799cd1f81f9956f03a0e1d9a861e020a598dd411d9bd3c3c1dd5b8a4/torch_cluster-1.4.4.tar.gz"
  sha256: "7907f3f270116cb299bdd4f88de497a85b3b34cf127910ffe0a6131e16620123"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - scipy
    - pytorch ==1.1.0
    - pytest-runner
  run:
    - python
    - scipy

test:
  imports:
    - torch_cluster
  requires:
    - pytorch ==1.1.0
    - pytest
    - pytest-cov

about:
  home: "https://github.com/rusty1s/pytorch_cluster"
  license: "UNKNOWN"
  license_family: "OTHER"
  license_file: ""
  summary: "PyTorch Extension Library of Optimized Graph Cluster Algorithms"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
