{% set name = "torch-scatter" %}
{% set version = "1.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
#  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  url: "https://files.pythonhosted.org/packages/35/d4/750403a8aa32cdb3d2d05849c6a10e4e0604de5e0cc94b81a0d0d69a75f3/torch_scatter-1.3.1.tar.gz"
  sha256: "54cbad248350165ddc921ded3fe7a69be5d30c6536273a1a3282e375289f86ec"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - pytest-runner
    - pytorch ==1.1.0
  run:
    - python

test:
  imports:
    - torch_scatter
    - torch_scatter.utils
  requires:
    - pytorch ==1.1.0
    - pytest
    - pytest-cov

about:
  home: "https://github.com/rusty1s/pytorch_scatter"
  license: "UNKNOWN"
  license_family: "OTHER"
  license_file: ""
  summary: "PyTorch Extension Library of Optimized Scatter Operations"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - your-github-id-here
